### ISSUE TITLE
pytest-assume does not FAIL in fixtures

### ISSUE THREAD

**Issue by reddypdl** [astraw38/pytest-assume#13]
Why is pytest.assume does NOT report failures in fixtures

e.g. 
import pytest

@pytest.fixture()
def before():
    **pytest.assume(False, "I am failed - before")**
    print('\nbefore each test')
 
def test_1(before):
    pytest.assume(False, "I am failed - test_1")
    print('test_1()')

**pytest test3.py**
============================= test session starts =============================
platform win32 -- Python 2.7.15, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('c:\\Temp\\.hypothesis\\examples')
rootdir: c:\Temp, inifile:
plugins: rerunfailures-6.0, repeater-0.1.1, repeat-0.8.0, random-0.2, json-0.4.0, cov-2.6.1, assume-1.2.2, hypothesis-4.14.2
collected 1 item

test3.py F                                                               [100%]

================================== FAILURES ===================================
___________________________________ test_1 ____________________________________
test3.py:9: AssumptionFailure
        I am failed - test_1
------------------------------------------------------------
Failed Assumptions: 1
---------------------------- Captured stdout setup ----------------------------

before each test
---------------------------- Captured stdout call -----------------------------
test_1()

**Comment by astraw38** [comment]
Right, that's partially by intent. 

The idea is that failed assumptions do not stop the test from proceeded -- triggering a fail during setup will block the test from proceeded. 

However, I *do* think that there is a bug in that the failed assumption in the fixture should still fail the test post-completion (and should show up in the failed assumption list).


I'll investigate a fix.

**Comment by reddypdl** [comment]
A failed assumption at any place should result in failure of test and it is expected behavior.

**Comment by astraw38** [comment]
At that point, you should really be using plain assertions (what use is a fixture if it doesn't do what it says it does?). Making pytest.assume work for fixtures would be a ton of effort for supporting what really is a bad practice in testing. 

It really is a *lot* of effort in that I'd basically have to replicate fixture tracking in pytest. In short: won't fix. I'd accept PRs that would take it on, but I'm not going to work on it myself.

**Comment by reddypdl** [comment]
If we can change **if call.when == "call" and failed_assumptions:**  in pytest_runtest_makereport to **if  call.when in ("call", "setup", "teardown") and failed_assumptions:**, then it should work seamlessly . 

Let me know if you still need a PR.

**Comment by astraw38** [comment]
That would make it so that any assumption failures in the setup block the call of the test itself (that's build into pytest), which as I said before, is counter what the plugin is supposed to do.
