### ISSUE TITLE
How to add custom hooks to this plugin ?

### ISSUE THREAD

**Issue by ptrivedi2610** [astraw38/pytest-assume#17]
Hi,

I would like to extend this assume plugin to provide few hooks. The reason is that every time assumption fails, I would like to set few variables that are in my conftest.py.

Can someone please guide me how to do the same ?
Thanks in advance

**Comment by geekyprats** [comment]
Appreciate earliest help.

**Comment by astraw38** [comment]
I would look at https://github.com/astraw38/pytest-assume/blob/master/pytest_assume/plugin.py#L61 in the code. 

If you implement the same hook (with hookwrapper=True, and outcome=yield) in your conftest or plugin, you should be able to catch the AssumptionFailure exception & do what you want at that point.

**Comment by geekyprats** [comment]
Hi @astraw38 

I think I will still not be able to achieve what I want.

Let me explain a bit in detail.

What I really need is  a hook like "pytest_assertrepr_compare", that would land me in a custom hook implementation on every pytest.assume() call

So on every pytest.assume(), I would set/reset a global variable.
How can I achieve this ?

**Comment by astraw38** [comment]
That's not supported right now -- but you could implement that yourself ([pytest docs](https://docs.pytest.org/en/latest/writing_plugins.html#declaring-new-hooks)

**Comment by astraw38** [comment]
Fixed in #19
