### ISSUE TITLE
Unable to see pytest assume failure information in Allure.

### ISSUE THREAD

**Issue by shinobi01** [astraw38/pytest-assume#22]
Environment:
Python 3.7.3
Pytest 5.0.0
Allure-pytest 2.7.0

Code snippets:
import pytest

def add(a, b):
return a + b

def test_add1():
assert add(3, 4) == 7

def test_add2():
pytest.assume(add(1, 2) == 4)
print('run?')
pytest.assume(add(2, 2) == 5)
print('done')

def test_add3():
assert add(4, 5) == 8

if name=='main':
pytest.main("Workflow 1.py")

![Untitled](https://user-images.githubusercontent.com/19482522/61275310-47c33880-a7e0-11e9-9ea3-fbaffa8b5212.png)

The failed information could be seen in pytest-html.

**Comment by astraw38** [comment]
Hi @shinobi01 , can you try it w/ pytest-assume 2.x? In the meantime, I'll look into allure to see if I can reproduce.

**Comment by shinobi01** [comment]
Hi @astraw38, thanks for your reply, I tried this w/ pytest-assume 2.1 on my Mac, the failure info could be seen in Allure. I'll try it on windows tomorrow.
Thanks again.

**Comment by shinobi01** [comment]
Hi @astraw38 , I tried this issue on Windows, it also gone. Thanks for your information. I'll closed this issue.

**Comment by astraw38** [comment]
great! thanks for double checking
