### ISSUE TITLE
Context manager

### ISSUE THREAD

**Issue by dimaqq** [astraw38/pytest-assume#3]
Please allow (or document if already supported) following syntax sugar:

```
def test_foo():
    with assume:
        assert 0
    with assume:
        assert 1
```

**Comment by astraw38** [comment]
Perhaps you might want:

```py
with pytest.raises(AssertionError):
     assert 0
``` 

instead? Or do you want the test to continue regardless of the result of that context? 

Either way, you will likely still run into problems if you do something like:

```py

with assume():
     assert 0
     assert 1
```

And the second assert would never be run.
