### ISSUE TITLE
Getting error while running bind hooks from pytest-assume plugin while running the executable generated from "PyInstaller"

### ISSUE THREAD

**Issue by ptrivedi2610** [astraw38/pytest-assume#31]
Recently I have been working on a Project that requires to create an executable that includes the source code and some hooks from pytest-assume plugin of pytest library.
When the .exe file is executed, there arises an error regarding the usage of hooks, as below

collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR> File "_pytest\main.py", line 185, in wrap_session
INTERNALERROR> File "_pytest\main.py", line 224, in _main
INTERNALERROR> File "pluggy\hooks.py", line 258, in call
INTERNALERROR> File "pluggy\manager.py", line 67, in _hookexec
INTERNALERROR> File "pluggy\manager.py", line 61, in
INTERNALERROR> File "pluggy\callers.py", line 201, in _multicall
INTERNALERROR> File "pluggy\callers.py", line 76, in get_result
INTERNALERROR> File "pluggy\callers.py", line 180, in _multicall
INTERNALERROR> File "_pytest\main.py", line 234, in pytest_collection
INTERNALERROR> File "_pytest\main.py", line 448, in perform_collect
INTERNALERROR> File "pluggy\manager.py", line 241, in check_pending
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_assume_fail' in plugin <module 'conftest' from 'C:\Users\PT\Desktop\dist\conftest.py'>

Is there a proper method in a way that such hooks from plugins are detected. Note that the pytest-assume plugin is successfully found by the executable. Seems the hooks are not registered.

Kindly help for the same.
Pasting spec file content for reference.

========================================================

-- mode: python ; coding: utf-8 --
block_cipher = None

a = Analysis(['main.py'],
pathex=[
os.path.join(DISTPATH, 'obf', 'temp'),
'.',
'C:\Python37\Lib\site-packages',
'C:\Python37\Lib\site-packages\pytest-assume',
'C:\Python37\Lib\site-packages\py',
'C:\Python37\Lib\site-packages\pluggy',
'C:\Python37\Lib\site-packages\xmlschema',
'C:\Python37\Lib\urllib',
'C:\Python37\Lib\site-packages\xmlschema\validators\schemas\XSD_1.0'],
binaries=[],
datas=[],
hiddenimports=['pytransform', 'py.io'],
hookspath=[os.path.join(DISTPATH, 'obf', 'temp')],
runtime_hooks=[],
excludes=[],
win_no_prefer_redirects=False,
win_private_assemblies=False,
cipher=block_cipher,
noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
cipher=block_cipher)
exe = EXE(pyz,
a.scripts,
[],
exclude_binaries=True,
name='main',
debug=False,
bootloader_ignore_signals=False,
strip=False,
upx=True,
console=True )
coll = COLLECT(exe,
a.binaries,
a.zipfiles,
a.datas,
strip=False,
upx=True,
upx_exclude=[],
name='main')

I am using Windows 10 platform.
Any help would be much appreciated.

**Comment by astraw38** [comment]
Out of curiosity, how do you specify that you are using the plugin? via something like ``pytest_plugins=["pytest_assume"]`` in a conftest? Or are you just installing the plugin & using it automatically? 

So some additional debug info that might help:

1. you can run pytest + your tests outside of a built PyInstaller exe & it works, right?
2. What does the pytest header say about plugins used/installed? It'll be above the 'collecting...' lines. Usually has things like 'pluggy==0.1.1' in it.

**Comment by ptrivedi2610** [comment]
@astraw38 
Yes in my project, I use it automatically after installation. Should I specify in conftest "pytest_plugins=["pytest_assume"]" as well ?

What I have observed is that the pytest registration hook inside assume plugin "pytest_configure" is not called in case of execution by creating executable from PyInstaller

**Comment by astraw38** [comment]
My suspicion is that the plugin isn't being loaded by pytest. If you add that line to the conftest, pytest will fail fast & let us know that the plugin isn't found. The other output i requested would also show if the plugin is loaded.

**Comment by ptrivedi2610** [comment]
@astraw38  Thank you for all the help and pointers. 
I have one question. Are the hooks created by me in perfect format ?  Did I miss something in the implementation that may have caused things to break ? Kindly review and help me

**Comment by astraw38** [comment]
The hooks are implemented correctly.


Can you *please* verify that the plugin is being loaded when you build the exe? I've asked 3x now for info about whether the plugin is even showing up in pytest when you build the exe. 

When you run pytest, you should see a header that shows all the loaded plugins, You need to verify that pytest-assume is in that list when you run your exe:

For example:
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.6.0, py-1.7.0, pluggy-0.13.0 -- /usr/local/bin/python2.7
cachedir: .pytest_cache
rootdir: /home/astraw/, inifile: pytest.ini
plugins: instafail-0.4.1, assume-2.2.0, forked-1.0.2, xdist-1.27.0
```


If your plugin isn't even showing there, then it's an issue with how PyInstaller is building your exe.

**Comment by ptrivedi2610** [comment]
@astraw38 
You are right, it does throw error. Seems after bundling, the executable is unable to find pytest-assume.

I referred pytest standard documentation and this is what it says (Pytest doc: **Section 27.2.13**)
**If you freeze your application using a tool like PyInstaller in order to distribute it to your end-users, it is a good idea
to also package your test runner and run your tests using the frozen application. This way packaging errors such as
dependencies not being included into the executable can be detected early while also allowing you to send test files to
users so they can run them in their machines, which can be useful to obtain more information about a hard to reproduce
bug.
Fortunately recent PyInstaller releases already have a custom hook for pytest, but if you are using another tool
to freeze executables such as cx_freeze or py2exe, you can use pytest.freeze_includes() to obtain the
full list of internal pytest modules. How to configure the tools to find the internal modules varies from tool to tool,
however.
Instead of freezing the pytest runner as a separate executable, you can make your frozen program work as the pytest
runner by some clever argument handling during program startup. This allows you to have a single executable, which
is usually more convenient. Please note that the mechanism for plugin discovery used by pytest (setupttools entry
points) doesn’t work with frozen executables so pytest can’t find any third party plugins automatically. To include
third party plugins like pytest-timeout they must be imported explicitly and passed on to pytest.main.


import sys
import pytest_timeout # Third party plugin
if len(sys.argv) > 1 and sys.argv[1] == "--pytest":
import pytest
sys.exit(pytest.main(sys.argv[2:], plugins=[pytest_timeout]))
else:
# normal application execution: at this point argv can be parsed
# by your argument-parsing library of choice as usual**

**Comment by ptrivedi2610** [comment]
@astraw38 
Seems I had to add hooks-pytest_assume.py file to the hook mechanism of pyinstaller that solved the issue.
