### ISSUE TITLE
pytest.assume causes exception from its library when used with PyInstaller

### ISSUE THREAD

**Issue by ptrivedi2610** [astraw38/pytest-assume#32]
@astraw38 

Currently in my project, I have used pytest-assume 3rd party plugin using the hook of pyinstaller. I have created hook-pytest_assume.py to fetch the plugin from system.

The issue here is that when my project code is executed, pytest-assume library crashes from within. If I don't create executable it works fine.

Is there any specific process that happens when I include pytest-assume via hooks ?

I am attaching both hook file and the crash that arises.

===========================
**Hook File Content**

from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('pytest_assume')

===========================
**Crash**

_____________________________________________________________________ Test_1.test_trigger _____________________________________________________________________
:550: in read_func
???
pytest_assume\plugin.py:121: in call
assert expr
pytest_assume\plugin.py:79: in exit
context = contextlist[0].lstrip()
E TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:
pytest_assume\plugin.py:119: in call
assert expr, msg
E AssertionError: read_func ERROR : 'NoneType' object is not subscriptable
E assert False

During handling of the above exception, another exception occurred:
..\Test_1.py:56: in test_trigger
status, response = read_func(params)
:630: in read_func
???
E TypeError: 'NoneType' object is not subscriptable

**Comment by astraw38** [comment]
Fixed via #33  -- thanks again!
