### ISSUE TITLE
Getting "Cannot find reference 'assume' in '__init__.py'" trying to import

### ISSUE THREAD

**Issue by pmneve** [astraw38/pytest-assume#47]
Here is code snippet:
`# -*- coding: utf-8 -*-

import pytest
from pytest import **_assume_**

class TestUiPublicExhibit:

    def test_ui_landing_header(self, exhibit):
        landing_page = exhibit
        with assume: assert landing_page.verify_brand_image()
`
What am I missing?

**Comment by astraw38** [comment]
Use:

```py

import pytest

def test_simple():
    with pytest.assume:
         assert False
```

Pytest used to have a hook called ``pytest_namespace`` iirc that would let you do as you want (you could add to the namespace dynamically), but it was deprecated in favor of monkeypatching it in during pytest_configure.
