### ISSUE TITLE
`from pytest import assume` breaks `sphinx-apidoc` if tests not excluded

### ISSUE THREAD

**Issue by akaihola** [astraw38/pytest-assume#56]
The `README` has this example:

```python
import pytest
from pytest import assume
    
@pytest.mark.parametrize(('x', 'y'), [(1, 1), (1, 0), (0, 1)])
def test_simple_assume(x, y):
    with assume: assert x == y
    with assume: assert True
    with assume: assert False
```

In a project with such a test module inside the top-level Python package, running `sphinx-apidoc -o api ../mypkg` will throw:
```
WARNING: autodoc: failed to import module 'test_mymod' from module 'mypkg.tests';
         the following exception was raised:
cannot import name 'assume' from 'pytest' (lib/python3.9/site-packages/pytest/__init__.py)
```

To prevent this, it's important to exclude the tests directory by invoking:
```bash
sphinx-apidoc -o api ../mypkg ../mypkg/tests
```

I wanted to mention this in the public so anyone else searching for this problem will find the root cause quicker.

**Comment by astraw38** [comment]
This will happen if the pytest hooks are not executed -- which would happen during sphinx parsing. You could import directly from the plugin (`from pytest_assume.plugin import assume` I believe). Ideally, readme & __init__.py would be updated to make the easier & clearer - and make breaking downstream tooling less likely.
